


mysql:
  url: jdbc:mysql://localhost:3306/TESTDB?useSSL=false 
  driverClassName: com.mysql.jdbc.Driver
  username: cwkim
  password: 1111
  
  
#logging:
#  path: logs  
  
  

#debug: true 



lateif:
  timeout: 2
  
api:
  key: X-API-KEY
  value: test1234  
  
  
  